
[34m[1mwandb[39m[22m:   4 of 4 files downloaded.
Traceback (most recent call last):
  File "/workspaces/mlops_Zoomcamp_2023/week2/homework-wandb/train.py", line 67, in <module>
    run_train()
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/workspaces/mlops_Zoomcamp_2023/week2/homework-wandb/train.py", line 61, in run_train
    artifact.add_file("regressor.pkl.pkl")
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/wandb/sdk/artifacts/local_artifact.py", line 377, in add_file
    raise ValueError("Path is not a file: %s" % local_path)
ValueError: Path is not a file: regressor.pkl.pkl